sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: XDJShn2cRfWc9kVsibmaxc1SwT/92xxeNt61PWJ+nFZ4flKZa3bQOiQwFjTNmrWHgUMn0PUvGNC3R4vrfAgEd63Id4ZDnFASfLrT1W5nKlY41+9eqly2FrlzyOpER8zBd7jMalyOnGp2aJo59Asbzco9rnXOTkRsZkp+d9GG5fEPUTKfxX0aD1TEkhrbVvyDSvQ+bg429IIwEOptOCx0sNO1hecu16QKtm2+LS3VVwIFVui/IrH+JHH/zHaJ0eRta+L2j21VJkFn5dR4CZUrDLpc8U0pGKmRwYIIsCXuI8nyKc201G4vIlsJ+4NB5FvYuc36KATHk7Ox+ZLCDV5UZp92irjl23+1sg2NsgjWikMwSC8176R4SSq9vZv025ieF+3HPRMPMGsUnrrxiLxNrcR4amJZ3Xk3Gz7ImG4jl/6Gupwtq3LlnbUY8VicUHSl9zyItyeHVCx1GhMDNxbGEJP/9RifLy1lk0/zSXMt9hiO7sWpcvXuZ8jCXA4aJ1rPj3/ua9DngbYBRw39fRJ8Z946wZfeFDz8wZqRT4EuErurhOLbJHRKNoLo4rrC5ligvo0102ZnZ1ypLsHCkiFZJeS9a0BD/2VJ1lOlUpEKieMVCZerQKTuMnCfglRUfcT6Y17xYhtWw53vyoG/x2/YyiFI46QXPOk2ZGjlQoR65pU=
branches:
  only:
  - master
dd:
  secure: jlOxryJBSJt3dc8b61KTGJ2dRLtLoZgbUkREQjXwc8RK5BkLlEj5UrBmERZh6x8/0DBNr2fh6k1n6G5K6DKduiFwWdXq5eRYPs7GSpZLyHyv+bynpNdpYz3+ttUEJYFH4CbglsxbnT2SDzfqfV+bya96LO4uoWJcP3L63I9SAESkhCvyItJzRMDl5YXn+Vw+0544fBV56XNcTBdzUClaSofsHLRbTs7oIT3p6ap/W1+09pCSgeKXQK9eXa5pdtg41+iihSJrj/irs7avGk6ejvja0iZ92aiwJfrYldPBWwtJJtOZSbyXl2DEBQZ4Xn7p10B3DCrxo+0cBHmVP0T/MUZZdxgsXMfeso515Hqzw8x/FOnjN8xiV3dDhC1hz0+dCxVLQ7ADxc5ER4m92L9gXEq9bDwAGQJJOrp2glLYfJ0FPfilkQUnVjm4s9hxs6klNc/YEriSeBDJkSipqZTTwbofbYLWfycPz9fm68ZuniYiqi3086mMV4PfwU6rv302keaZFiC0hcbreJ6jkNrHcHnXKrG1REBHuTsdhX+IkGORt9BxoodC9boQWU2gxxPywRaDBFrc1sl5FPra5QIqI1kl4yuG3ovPwXlJVk8ItF0p8XcUPTCc2BQplMxTIkskyvFQ5yp5ks+yp4VcEo0OBAoCHuR+CAk2mpbJn2HkFAI=
