sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet

env:
  global:
    secure: XDJShn2cRfWc9kVsibmaxc1SwT/92xxeNt61PWJ+nFZ4flKZa3bQOiQwFjTNmrWHgUMn0PUvGNC3R4vrfAgEd63Id4ZDnFASfLrT1W5nKlY41+9eqly2FrlzyOpER8zBd7jMalyOnGp2aJo59Asbzco9rnXOTkRsZkp+d9GG5fEPUTKfxX0aD1TEkhrbVvyDSvQ+bg429IIwEOptOCx0sNO1hecu16QKtm2+LS3VVwIFVui/IrH+JHH/zHaJ0eRta+L2j21VJkFn5dR4CZUrDLpc8U0pGKmRwYIIsCXuI8nyKc201G4vIlsJ+4NB5FvYuc36KATHk7Ox+ZLCDV5UZp92irjl23+1sg2NsgjWikMwSC8176R4SSq9vZv025ieF+3HPRMPMGsUnrrxiLxNrcR4amJZ3Xk3Gz7ImG4jl/6Gupwtq3LlnbUY8VicUHSl9zyItyeHVCx1GhMDNxbGEJP/9RifLy1lk0/zSXMt9hiO7sWpcvXuZ8jCXA4aJ1rPj3/ua9DngbYBRw39fRJ8Z946wZfeFDz8wZqRT4EuErurhOLbJHRKNoLo4rrC5ligvo0102ZnZ1ypLsHCkiFZJeS9a0BD/2VJ1lOlUpEKieMVCZerQKTuMnCfglRUfcT6Y17xYhtWw53vyoG/x2/YyiFI46QXPOk2ZGjlQoR65pU=
branches:
  only:
  - source
