sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
    secure: Gju6BRu83Ypuat+xBM2WU7PktPaJM2JcAqA8+90TZHi2qcKW3om6tHrmujPBrd7hmBOqsSQq3uNbLUpVggL7Z+mFobKRmDo+2gI8a5a5+ns8NWTqhTL8z/N0U5qljz2P1aOYEgMYYd2GDw2BcfRkhXDNFMsqyewtlXG8xfb7nTfgPiOVTKVlcpN80LsS90d4NJPFAXxKtMsZ4YnRJZ2sUnga7m/inIl1B6cvFfIvskqjjcvSt88CgdIbyYaq631CTWbvfM/+USySzXzttCOrPEIkp3Uqzch+w5ItvJSZ5LToVykTbMwzv+WuP9aFMXz9jK3RBtOW6uQA5g09W8fb7e9sfRB7Ro4VF+QrAPMknq9u0oXtXsBrtVXtypKx8Rp4II540E05x9PfMm4hvbUTDkwG1qCBVo55ZTUBQai/GA7lfT0KSbIxrRru9VxW6uSQhMJNy5ULo7hdjUFMKQdrG46n+/sgB+g1n5bLvfwTa268aaOkYE0tYOkz3/9kCmgnD1jMtFO/sMrn3NLKWsNjROePpcxFwam+u1CecYNzt7i7H6czROSHEowSy6ebTHQbRJlv5aNdPixoBdjata8XKue8eqYXDQo8OU43NL7soX3RNsgjo1l/o53GqO5tZsduCEzgdy9z+i5/ccYmBYWqoqckcxmy2ibMYrPDdvcfTMQ=
