title: Interactuar Objetos
subtitle: Cosas lindas
description: Decoración de interiores · Estudio de diseño de interiores
author: Marian
email: your-email@example.com
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "/interactuarobjetos" # the subpath of your site, e.g. /blog
url: "https://espaciocentenera.github.io" # the base hostname & protocol for your site

# Social settings
facebook_url: https://www.facebook.com/fuegoazulobjetos
github_url:
googleplus_url:
instagram_url: https://www.instagram.com/fuegoazulobjetos/
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# Plugins
plugins:
  - jekyll-gallery-generator

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
collections: [sections]

# Gallery
gallery:
  dir: assets/fotos               # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Fotos"           # Title for gallery index page
  title_prefix: "fotos: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  hidden: true
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    tatami:
      best_image: tatami1.jpg  # The image to show on the gallery index page. Defaults to the last image.
      hidden: true
    #japan_trip:
     # best_image: IMG_0690.JPG
     # name: "日本の旅"       # Defaults to directory name, replacing _ with spaces & capitalizing words.
    #awesome_stuff:
     # best_image: snaileo_gonzales.jpg
      #sort_reverse: true    # Reverse sort images in gallery.
    #secret_stuff:
     # hidden: true          # Don't show this gallery on the index page. People must guess the URL.
    with_info:
      info:
        desc: "Gallery Description" # Info fields can be used in custom templates.



# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: espaciocentenera
repo: interactuarobjetos
branch: master
relative_source: ../
destination: ../interactuar/
production_url:  https://espaciocentenera.github.io/interactuarobjetos
source_url:  https://github.com/EspacioCentenera/interactuarobjetos

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - jekyll-gallery-generator-master.zip
